# SPDX-FileCopyrightText: Copyright 2021 M2mobi B.V., Amsterdam, The Netherlands
# SPDX-FileCopyrightText: Copyright 2022 Move Agency Group B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: PHP Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  php-tests:
    uses: pprkut/lunr-actions/.github/workflows/php-composer.yml@framna
    with:
      coding-standard: 'Lunr'
      minimum-php-version: '8.3'
      stable-php-versions: '["8.3"]'
      experimental-php-versions: '["8.4","8.5"]'
      phpcs-whitelist: tests/phpstan.autoload.inc.php tests/test.bootstrap.inc.php
      php-extensions: uopz
